### ISSUE TITLE
[Request] CookieWars

### ISSUE THREAD

**Issue by Elbod** [Citillara/CitiBot#28] opened 2017-10-20 20:09 UTC
Similar to Bidwars, A good use to burn cookies is to use them for user choices, the choice with more cookies is the one what wins. Example:

**What to play tomorrow?**
!cookiewar FF8 <cuantity>
or
!cookiewar TombRaider <cuantity>

So the choice who got more cookies given, will be the result of tomorrow's stream. This can be aplied to pretty much anything, like choice of diferent endings, polls... all in a free manner, and with heavy focus on actual active users in the channel.

It would be +100 internet points if the actual streamer (or mods) could set the options manually, in case someone types FF89 instead of FF8, it would return something like: Current Cookiewars are FF8 and TombRaider.

What do you think? Good or bad idea?

**Comment by Citillara** [comment] 2017-11-07 22:51
Duplicate of #19

**Closed as completed** 2017-11-07 22:52 UTC
